import org.codehaus.groovy.runtime.GStringImpl
import org.gradle.internal.os.OperatingSystem

buildscript {
    repositories {
        maven { url "https://maven.aliyun.com/repository/public/" } // Aliyun Mirrors
        maven { url "https://maven.aliyun.com/repository/gradle-plugin/" }
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        classpath "org.openjfx:javafx-plugin:0.0.13"
    }
}


allprojects {
    apply plugin: "eclipse"
    apply plugin: "java-library"
    apply plugin: "org.openjfx.javafxplugin"

    version = "3.9.2"
    ext {
        // App Metadata
        appName = "ArkPets"
        appAuthor = "Harry Huang"
        appYearBegin = "2022"
        appYearCurrent = new Date().format("yyyy", TimeZone.getTimeZone("GMT+0:00"))
        appCopyright = "Copyright (c) ${appYearBegin}-${appYearCurrent} ${appAuthor}" as GStringImpl
        // Prefabs
        gdxVersion = "1.11.0"
        jnaVersion = "5.12.1"
        javaFXVersion = "17.0.8"
        dbusVersion = "5.1.0"
        lwjglVersion = "3.3.4"
        javaFXPlatform = ""
        lwjglPlatform = ""
        def isArm = System.getProperty("os.arch").startsWith("aarch64")
        def isX64 = System.getProperty("os.arch").contains("64")
        if (forceJavaFXPlatform.empty) {
            switch (OperatingSystem.current()) {
                case OperatingSystem.LINUX:
                    javaFXPlatform = "linux"
                    break
                case OperatingSystem.WINDOWS:
                    javaFXPlatform = isX64 ? "win" : "win-x86"
                    break
                case OperatingSystem.MAC_OS:
                    javaFXPlatform = isArm ? "mac-aarch64" : "mac"
                    break
            }
        } else {
            javaFXPlatform = forceJavaFXPlatform
        }
        if (forceLWJGLPlatform.empty) {
            switch (OperatingSystem.current()) {
                case OperatingSystem.LINUX:
                    lwjglPlatform = "natives-linux"
                    break
                case OperatingSystem.WINDOWS:
                    lwjglPlatform = isX64 ? "natives-windows" : "natives-windows-x86"
                    break
                case OperatingSystem.MAC_OS:
                    lwjglPlatform = isArm ? "natives-macos-arm64" : "natives-macos"
                    break
            }
        } else {
            lwjglPlatform = forceLWJGLPlatform
        }
    }

    repositories {
        maven { url "https://maven.aliyun.com/repository/public/" } // Aliyun Mirrors
        mavenLocal()
        mavenCentral()
    }
}

println "Building ArkPets for LWJGL ${lwjglPlatform} JavaFX ${javaFXPlatform}."

project(":desktop") {
    dependencies {
        implementation project(":core")
        // libGDX Desktop
        api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
        api "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
    }
}


project(":core") {
    dependencies {
        // Spine Runtime
        api "com.esotericsoftware.spine:spine-libgdx:3.8.99.1"
        // libGDX
        api "com.badlogicgames.gdx:gdx:$gdxVersion"
        api("com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion") {
            exclude group:"org.lwjgl"
        }
        api ("com.badlogicgames.gdx:gdx-lwjgl3-angle:$gdxVersion"){
            exclude group:"org.lwjgl"
        }
        // JNA
        api "net.java.dev.jna:jna:$jnaVersion"
        api "net.java.dev.jna:jna-platform:$jnaVersion"
        // JavaFX
        api "org.openjfx:javafx-base:$javaFXVersion:$javaFXPlatform"
        api "org.openjfx:javafx-controls:$javaFXVersion:$javaFXPlatform"
        api "org.openjfx:javafx-graphics:$javaFXVersion:$javaFXPlatform"
        api "org.openjfx:javafx-fxml:$javaFXVersion:$javaFXPlatform"
        // JFoenix
        api "com.jfoenix:jfoenix:9.0.1"
        // FastJson
        api "com.alibaba:fastjson:2.0.39"
        // CommonMark
        api "org.commonmark:commonmark:0.24.0"
        api "org.commonmark:commonmark-ext-autolink:0.24.0"
        api "org.commonmark:commonmark-ext-gfm-strikethrough:0.24.0"
        api "org.commonmark:commonmark-ext-gfm-tables:0.24.0"
        // dbus-java
        api "com.github.hypfvieh:dbus-java-core:$dbusVersion"
        api "com.github.hypfvieh:dbus-java-transport-native-unixsocket:$dbusVersion"
        // LWJGL
        def lwjglList = ["lwjgl", "lwjgl-opengl","lwjgl-opengles", "lwjgl-stb", "lwjgl-openal", "lwjgl-jemalloc", "lwjgl-glfw"]
        lwjglList.each {
            api "org.lwjgl:${it}:${lwjglVersion}"
            api "org.lwjgl:${it}:${lwjglVersion}:${lwjglPlatform}"
        }
        api "org.lwjgl:lwjgl-egl:${lwjglVersion}"
        // reload4j
        api "ch.qos.reload4j:reload4j:1.2.26"
        // TiniPinyin
        api 'com.github.promeg:tinypinyin:2.0.3'
        // OpenCC4j
        api 'com.github.houbb:opencc4j:1.8.1'
    }
}
