name: Build

on: workflow_dispatch

jobs:
  buildWin:
    runs-on: windows-latest
    steps:
      - name: Check Ref
        run: |
          echo "Current ref: ${{  github.ref  }}"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.1.1

      - name: Execute Gradle Tasks
        run: gradle clean distAll

      - name: Upload Exe
        uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: ArkPets.exe
          path: desktop/build/dist/*.exe

      - name: Upload Zip
        uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: ArkPets.zip
          path: desktop/build/dist/*.zip

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: ArkPets.jar
          path: desktop/build/dist/*.jar
  buildMac:
    runs-on: macos-latest
    steps:
      - name: Check Ref
        run: |
          echo "Current ref: ${{  github.ref  }}"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Setup create-dmg
        run: brew install create-dmg

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.1.1

      - name: Execute Gradle Tasks
        run: gradle clean distDmg
      - name: Upload DMG
        uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: ArkPets.dmg
          path: desktop/build/dist/*.dmg
