plugins {
    id "arkpets-conventions"
    id "arkpets-dist"
}

sourceSets.main.java.srcDirs = ["src/"]
sourceSets.main.resources.srcDirs = ["../assets"]

dependencies {
    implementation project(":core")
    // libGDX Desktop
    api variantOf(libs.gdx.platform) {
        classifier('natives-desktop')
    }
}

processResources {
    includeEmptyDirs = false
    excludes = [
            "**/models_enemies/**",
            "**/models/**",
            "**/logs/**",
            "models_data.json"
    ]
}
